'use client';
import {Component,useCallback,useEffect,useMemo,useRef,useState,type ReactNode} from 'react';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import Image from 'next/image';
import {ArrowLeft,Play,Pause,RotateCcw,Download,Upload,Database,GitMerge,Braces,Layers,CheckCircle2,HelpCircle} from 'lucide-react';
import {DEFAULT_CONFIG,DEFAULT_SQL,parseCSV,pipeline,quality,sample,toCSV,type Table,type Stage,type Config} from '@/lib/dataflow/engine';
import s from './dataflow.module.css';
const Scene=dynamic(()=>import('./FlowScene'),{ssr:false,loading:()=> <div className={s.loading}>Preparando o laboratório 3D…</div>});
const titles=['Fontes','Limpeza','Filtro','Junção','SQL'];
type Run={sources:ReturnType<typeof sample>;stages:Stage[];config:Config;sql:string;truncated:boolean;name:string;at:string};
class SceneBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true};}render(){return this.state.failed?<div className={s.loading}>3D indisponível neste dispositivo. Continue pela visão 2D ou pelos botões das etapas abaixo.</div>:this.props.children;}}
function download(name:string,text:string,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function DataTable({table,label}:{table:Table;label:string}) {
  const [page,setPage]=useState(0);useEffect(()=>setPage(0),[table]);const pages=Math.max(1,Math.ceil(table.rows.length/30));const safePage=Math.min(page,pages-1);
  return <section className={s.tablePanel}><div className={s.tableHead}><strong>{label}</strong><span>{table.rows.length.toLocaleString('pt-BR')} linhas · {table.columns.length} colunas</span></div><div className={s.tableScroll}><table><thead><tr>{table.columns.map((c,i)=><th key={i}>{c}</th>)}</tr></thead><tbody>{table.rows.slice(safePage*30,safePage*30+30).map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j} title={v===null?'NULL':String(v)}>{v===null?<em>NULL</em>:String(v)}</td>)}</tr>)}</tbody></table>{!table.rows.length&&<p className={s.empty}>Nenhum registro nesta etapa.</p>}</div><div className={s.pagination}><button disabled={safePage===0} onClick={()=>setPage(p=>p-1)}>Anterior</button><span>{safePage+1} / {pages}</span><button disabled={safePage>=pages-1} onClick={()=>setPage(p=>p+1)}>Próxima</button></div></section>;
}
function Chart({table}:{table:Table}) {
  const ni=table.columns.findIndex((_,i)=>table.rows.some(r=>typeof r[i]==='number'));
  const valueIndex=table.columns.findIndex((c,i)=>i>ni&&table.rows.some(r=>typeof r[i]==='number'));
  const metric=valueIndex<0?ni:valueIndex;
  const label=table.columns.findIndex((_,i)=>table.rows.some(r=>typeof r[i]==='string'));
  if(metric<0||label<0||!table.rows.length)return <p className={s.hint}>Retorne uma coluna de texto e uma numérica no SQL para visualizar barras.</p>;
  const max=Math.max(1,...table.rows.slice(0,12).map(r=>Math.abs(Number(r[metric])||0)));
  return <div className={s.chart}><div className={s.eyebrow}>{table.columns[metric]} · primeiras 12 linhas</div>{table.rows.slice(0,12).map((r,i)=><div className={s.barRow} key={i}><span>{String(r[label]??'NULL')}</span><div><i style={{width:`${Math.abs(Number(r[metric])||0)/max*100}%`}}/></div><b>{Number(r[metric]||0).toLocaleString('pt-BR')}</b></div>)}</div>;
}
export default function DataFlowLab({demo=false}:{demo?:boolean}) {
  const [data,setData]=useState(sample),[config,setConfig]=useState<Config>(DEFAULT_CONFIG),[sql,setSql]=useState(DEFAULT_SQL),[name,setName]=useState('Caso Aurora · vendas'),[run,setRun]=useState<Run|null>(null),[previous,setPrevious]=useState<Run|null>(null);
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[dirty,setDirty]=useState(false),[selected,setSelected]=useState(0),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[view,setView]=useState<'3d'|'2d'>('3d'),[reset,setReset]=useState(0),[help,setHelp]=useState(false),[reduced,setReduced]=useState(false),[hidden,setHidden]=useState(false);
  const worker=useRef<Worker|null>(null),timer=useRef<ReturnType<typeof setTimeout>>(),runRef=useRef<Run|null>(null),helpRef=useRef<HTMLDialogElement>(null);
  const execute=useCallback((input:typeof data,c:Config,query:string,label:string)=>{
    worker.current?.terminate();clearTimeout(timer.current);setBusy(true);setError('');setPlaying(false);
    try {
      const stages=pipeline(input.orders,input.customers,c);const w=new Worker('/dataflow-worker.js');worker.current=w;
      const finish=()=>{w.terminate();if(worker.current===w)worker.current=null;clearTimeout(timer.current);setBusy(false);};
      timer.current=setTimeout(()=>{finish();setError('A consulta excedeu 8 segundos. Simplifique o SQL ou reduza os dados.');},8000);
      w.onerror=()=>{finish();setError('Não foi possível iniciar o SQL local. Recarregue a página e tente novamente.');};
      w.onmessage=({data:result}:{data:{error?:string;table:Table;truncated:boolean}})=>{finish();if(result.error){setError(result.error);return;}const next:Run={sources:input,stages:[...stages,{title:'SQL',table:result.table,note:result.truncated?'Resultado limitado a 1.000 linhas, inclusive na exportação. Refine a consulta.':'Consulta executada sobre a tabela fluxo após a junção.'}],config:{...c},sql:query,truncated:result.truncated,name:label,at:new Date().toLocaleTimeString('pt-BR')};setPrevious(runRef.current);runRef.current=next;setRun(next);setDirty(false);setTime(0);setSelected(0);};
      w.postMessage({tables:{pedidos:input.orders,clientes:stages[1].table,fluxo:stages[3].table},sql:query});
    }catch(e){setError(e instanceof Error?e.message:'Não foi possível executar.');setBusy(false);}
  },[]);
  useEffect(()=>{execute(sample(),DEFAULT_CONFIG,DEFAULT_SQL,'Caso Aurora · vendas');return()=>{worker.current?.terminate();clearTimeout(timer.current);};},[execute]);
  useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduced(media.matches);const visibility=()=>{setHidden(document.hidden);if(document.hidden)setPlaying(false);};update();media.addEventListener('change',update);document.addEventListener('visibilitychange',visibility);return()=>{media.removeEventListener('change',update);document.removeEventListener('visibilitychange',visibility);};},[]);
  useEffect(()=>{if(!playing)return;const id=setInterval(()=>setTime(t=>{const next=Math.min(100,t+speed);if(next===100)setPlaying(false);setSelected(Math.min(4,Math.floor(next/25)));return next;}),120);return()=>clearInterval(id);},[playing,speed]);
  useEffect(()=>{if(help)helpRef.current?.showModal();else helpRef.current?.close();},[help]);
  const change=(patch:Partial<Config>)=>{setConfig(c=>({...c,...patch}));setDirty(true);};
  const select=(i:number)=>{setSelected(i);setTime(i*25);setPlaying(false);};
  async function importFile(file:File|undefined,target:'orders'|'customers') {
    if(!file)return;setError('');try {if(file.size>1024*1024)throw new Error('Use um CSV de até 1 MB.');const table=parseCSV(await file.text());setData(d=>({...d,[target]:table}));setName('Arquivos próprios');setDirty(true);if(target==='orders'){change({leftKey:table.columns[0],filterKey:table.columns[0],filter:false});setSql('SELECT * FROM fluxo LIMIT 100');}else change({rightKey:table.columns[0],dedupKey:table.columns[0],dedup:false});}catch(e){setError(e instanceof Error?e.message:'Arquivo inválido.');}
  }
  const stages=run?.stages,stage=stages?.[selected];const before=stages?(selected===1?run!.sources.customers:selected===2?stages[0].table:selected>0?stages[selected-1].table: null):null;
  const counts=stages?.map(v=>v.table.rows.length)||[];
  const q=useMemo(()=>quality(data.customers),[data.customers]);
  const mission=run?.name==='Caso Aurora · vendas'&&run.config.dedup&&run.config.filter&&counts[2]===20&&counts[3]===20;
  return <main className={s.app}>
    <header className={s.header}><Link href="/conta/ferramentas" className={s.back} aria-label="Voltar às ferramentas"><ArrowLeft size={18}/></Link><Image src="/drivedata-symbol.png" width={38} height={38} alt="DriveData Academy"/><div className={s.brand}>DataFlow <b>Lab</b><small>LABORATÓRIO DE DADOS · 4D</small></div><div className={s.headerRight}><span className={s.badge}>{demo?'DEMONSTRAÇÃO':'LABORATÓRIO'}</span><button aria-label="Como funciona" onClick={()=>setHelp(true)}><HelpCircle size={16}/><span>Como funciona</span></button></div></header>
    <div className={s.intro}><div><p className={s.eyebrow}>CONSTRUA. EXECUTE. INVESTIGUE.</p><h1>Veja seus dados <span>em movimento.</span></h1><p>Explore cada transformação. Descubra onde o resultado muda.</p></div><button className={s.primary} disabled={busy} onClick={()=>execute(data,config,sql,name)}><Play size={17}/>{busy?'Processando…':'Executar fluxo'}</button></div>
    {error&&<div role="alert" className={s.error}>{error} {run&&'A execução anterior continua disponível abaixo.'}</div>}
    <div className={s.workspace}>
      <aside className={s.sidebar}><div className={s.sideTitle}><Layers size={17}/><h2>Seu pipeline</h2><span>01—05</span></div>
        <fieldset disabled={busy}><section className={s.configSection}><h3><Database size={16}/>01 · Fontes de dados</h3><p className={s.hint}>CSV até 1 MB · 5.000 linhas · 40 colunas. Processado neste navegador.</p>{(['orders','customers'] as const).map((target,i)=><label className={s.upload} key={target}><span><strong>{i===0?'Pedidos':'Clientes'}</strong><small>{data[target].rows.length} linhas · {data[target].columns.length} colunas</small></span><Upload size={16}/><input type="file" accept=".csv,text/csv" aria-label={`Importar CSV de ${i===0?'pedidos':'clientes'}`} onChange={e=>{void importFile(e.target.files?.[0],target);e.target.value='';}}/></label>)}<p className={s.hint}>Clientes: {q.duplicates} linhas idênticas repetidas · {q.empty} células vazias.</p></section>
        <section className={s.configSection}><h3>02 · Limpeza de clientes</h3><label className={s.toggle}><input type="checkbox" checked={config.dedup} onChange={e=>change({dedup:e.target.checked})}/>Remover repetições pela chave</label><label className={s.field}>Chave única<select value={config.dedupKey} onChange={e=>change({dedupKey:e.target.value})}>{data.customers.columns.map(c=><option key={c}>{c}</option>)}</select></label></section>
        <section className={s.configSection}><h3>03 · Filtro de pedidos</h3><label className={s.toggle}><input type="checkbox" checked={config.filter} onChange={e=>change({filter:e.target.checked})}/>Manter somente registros iguais a</label><div className={s.fields}><select aria-label="Coluna do filtro" value={config.filterKey} onChange={e=>change({filterKey:e.target.value})}>{data.orders.columns.map(c=><option key={c}>{c}</option>)}</select><input aria-label="Valor do filtro" value={config.filterValue} onChange={e=>change({filterValue:e.target.value})}/></div></section>
        <section className={s.configSection}><h3><GitMerge size={16}/>04 · Junção</h3><label className={s.toggle}><input type="checkbox" checked={config.join} onChange={e=>change({join:e.target.checked})}/>Conectar pedidos aos clientes</label><div className={s.fields}><label className={s.field}>Pedidos<select value={config.leftKey} onChange={e=>change({leftKey:e.target.value})}>{data.orders.columns.map(c=><option key={c}>{c}</option>)}</select></label><label className={s.field}>Clientes<select value={config.rightKey} onChange={e=>change({rightKey:e.target.value})}>{data.customers.columns.map(c=><option key={c}>{c}</option>)}</select></label></div><p className={s.hint}>LEFT JOIN · preserva todos os pedidos. Tipos das chaves devem coincidir.</p></section></fieldset>
        <div className={s.mission}><span className={s.eyebrow}>MISSÃO / AURORA</span><h3>O faturamento fantasma</h3><p>Elimine a multiplicação de pedidos e mantenha apenas vendas aprovadas. Execute e compare.</p>{mission?<strong><CheckCircle2 size={16}/> Fluxo corrigido: 20 pedidos válidos!</strong>:<small>Dica: investigue a chave cliente_id e o status.</small>}<button disabled={busy} onClick={()=>{const fresh=sample();setData(fresh);setConfig({...DEFAULT_CONFIG});setSql(DEFAULT_SQL);setName('Caso Aurora · vendas');setDirty(true);setError('');}}>Carregar caso de exemplo</button></div>
      </aside>
      <div className={s.mainColumn}><section className={s.scenePanel}><div className={s.sceneToolbar}><div><span className={s.dot}/><strong>{run?.name||name}</strong><small>{busy?'Executando':dirty?'Alterações ainda não executadas':run?`Execução às ${run.at}`:'Preparando'}</small></div><div className={s.segment}><button aria-pressed={view==='3d'} onClick={()=>setView('3d')}>3D</button><button aria-pressed={view==='2d'} onClick={()=>setView('2d')}>2D</button><button aria-label="Restaurar câmera" onClick={()=>setReset(r=>r+1)}><RotateCcw size={15}/></button></div></div>
        <div className={s.scene}>{view==='3d'?<SceneBoundary><Scene counts={counts} selected={selected} onSelect={select} time={time} reset={reset} reduced={reduced||hidden}/></SceneBoundary>:<div className={s.flatFlow}>{titles.map((t,i)=><button key={t} onClick={()=>select(i)} aria-pressed={selected===i}><span>0{i+1}</span><Database size={28}/><b>{t}</b><small>{counts[i]??'—'} linhas</small></button>)}</div>}<div className={s.sceneCaption}>{view==='3d'?'Arraste para girar · role para aproximar · clique nas estações':'Selecione uma estação para inspecionar'}<br/>Partículas ilustrativas · contagens reais por etapa</div></div>
        <div className={s.steps}>{titles.map((t,i)=><button key={t} aria-pressed={selected===i} onClick={()=>select(i)}><small>0{i+1}</small>{t}<b>{counts[i]??'—'}</b></button>)}</div>
        <div className={s.timeline}><button disabled={!run||busy} aria-label={playing?'Pausar reprodução':'Reproduzir execução'} onClick={()=>{if(time===100)setTime(0);setPlaying(p=>!p);}}>{playing?<Pause size={18}/>:<Play size={18}/>}</button><div><label htmlFor="flow-time">REPRODUÇÃO DA EXECUÇÃO <span>{Math.round(time)}%</span></label><input id="flow-time" type="range" min={0} max={100} value={time} onChange={e=>{const v=Number(e.target.value);setTime(v);setSelected(Math.min(4,Math.floor(v/25)));setPlaying(false);}}/></div><select aria-label="Velocidade de reprodução" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={.5}>0,5×</option><option value={1}>1×</option><option value={2}>2×</option></select></div>
      </section>
      <section className={s.inspector}><div className={s.inspectorTitle}><div><p className={s.eyebrow}>INSPEÇÃO / {selected+1} DE 5</p><h2>{stage?.title||'Carregando dados'}</h2></div>{stage&&<button onClick={()=>download(`dataflow-${stage.title.toLowerCase()}.csv`,toCSV(stage.table),'text/csv;charset=utf-8')}><Download size={15}/>CSV da etapa</button>}</div><p className={s.note}>{stage?.note}</p>{stage&&<>{selected===1?<p className={s.hint}>Entrada: {stages?.[0].note} A limpeza atua somente na tabela de clientes.</p>:null}{before&&<details><summary>Ver entrada desta etapa ({before.rows.length} linhas)</summary><DataTable table={before} label="Antes da transformação"/></details>}<DataTable table={stage.table} label={selected===0?'Pedidos de origem':'Saída da etapa'}/>{selected===4&&<Chart table={stage.table}/>}</>}
      </section></div>
      <aside className={s.sqlPanel}><h2><Braces size={19}/>SQL Workbench</h2><p className={s.hint}>SQLite · consultas SELECT e WITH. A tabela <code>fluxo</code> recebe a saída da junção.</p><label htmlFor="flow-sql" className={s.eyebrow}>CONSULTA DO RESULTADO</label><textarea id="flow-sql" value={sql} disabled={busy} spellCheck={false} onChange={e=>{setSql(e.target.value);setDirty(true);}}/><button className={s.primary} disabled={busy} onClick={()=>execute(data,config,sql,name)}><Play size={15}/>{busy?'Executando…':'Executar fluxo + SQL'}</button><button onClick={()=>download('consulta-dataflow.sql',sql)}>Baixar SQL</button><div className={s.schema}><h3>Tabelas disponíveis</h3>{[{label:'pedidos',table:data.orders},{label:'clientes',table:data.customers},{label:'fluxo',table:stages?.[3].table}].map(({label,table})=><details key={label} open={label==='fluxo'}><summary><Database size={13}/>{label}</summary><p>{table?.columns.join(' · ')||'Execute o fluxo para ver as colunas.'}</p></details>)}<p className={s.hint}>clientes = após limpeza · pedidos = fonte original. O esquema de fluxo corresponde à última execução.</p></div>
      <section className={s.compare}><p className={s.eyebrow}>ANTES × AGORA</p><h3>Compare as execuções</h3>{previous&&run?<><p>{previous.at} → {run.at}</p><div><span>Linhas na junção</span><b>{previous.stages[3].table.rows.length} → {run.stages[3].table.rows.length}</b></div><div><span>Linhas no SQL</span><b>{previous.stages[4].table.rows.length} → {run.stages[4].table.rows.length}</b></div><details><summary>Ver SQL e resultado anteriores</summary><pre>{previous.sql}</pre><DataTable table={previous.stages[4].table} label={`${previous.name} · ${previous.at}`}/></details></>:<p>Execute uma mudança para comparar com o resultado anterior.</p>}</section><p className={s.hint}>Sessão temporária: baixe os resultados antes de sair. Nenhum arquivo é enviado ao servidor. Exportação CSV neutraliza fórmulas de planilha.</p></aside>
    </div>
    <dialog ref={helpRef} className={s.help} onCancel={()=>setHelp(false)} onClose={()=>setHelp(false)}><h2>Seu laboratório de dados em 4D</h2><p>As estações representam transformações reais. O tempo permite reproduzir uma execução concluída, pausar e investigar suas etapas; não representa a duração real de processamento.</p><ol><li>Explore o caso Aurora ou importe CSVs de pedidos e clientes.</li><li>Escolha as chaves, ative a limpeza e configure o filtro.</li><li>Escreva SQL sobre <code>fluxo</code> e execute.</li><li>Reproduza o caminho e inspecione tabelas antes e depois.</li><li>Compare com a execução anterior e baixe os resultados.</li></ol><p>A limpeza mantém o primeiro cliente de cada chave. Confira conflitos antes de usar essa regra em dados reais. CSV aceita vírgula ou ponto e vírgula; números decimais usam ponto. Valores como 001 ficam como texto.</p><p>Limites: 5.000 linhas por fonte, 10.000 na junção e 1.000 no resultado SQL. Consultas têm limite de 8 segundos. Dados e resultados ficam somente na memória desta aba.</p><button className={s.primary} onClick={()=>setHelp(false)}>Vamos explorar</button></dialog>
  </main>;
}
